export { RevolutXClient, type RevolutXClientOptions } from "./client.js";

export {
  buildAuthHeaders,
  signRequest,
  createTimestamp,
  generateKeypair,
  loadPrivateKey,
  getPublicKeyPem,
  loadCredentials,
  type Credentials,
} from "./auth/index.js";

export {
  getConfigDir,
  getConfigFile,
  getPrivateKeyFile,
  getPublicKeyFile,
  ensureConfigDir,
  loadConfig,
  saveConfig,
  isConfigured,
  type RevolutXConfig,
  DEFAULT_TIMEOUT_MS,
  DEFAULT_MAX_RETRIES,
} from "./config/settings.js";

export {
  RevolutXError,
  AuthenticationError,
  ForbiddenError,
  RateLimitError,
  ValidationError,
  BadRequestError,
  NotFoundError,
  ConflictError,
  ServerError,
  NetworkError,
  AuthNotConfiguredError,
} from "./http/index.js";

export {
  Logger,
  type LogLevel,
  type LogEntry,
  type LogCallback,
} from "./logging/logger.js";

export {
  paginateWithDynamicWindows,
  type PaginateOptions,
  type FetchPage,
  RATE_LIMIT_MAX_RETRIES,
  HISTORICAL_ORDERS_API_LIMIT,
  ACTIVE_ORDERS_API_LIMIT,
  TRADES_API_LIMIT,
  PAGINATED_DATA_MAX_LIMIT,
} from "./pagination/index.js";

export type {
  ErrorResponse,
  PaginationMetadata,
  PaginatedResponse,
  DataResponse,
  DataArrayResponse,
  PaginationOptions,
  DateRangeOptions,
  AccountBalance,
  Currency,
  CurrencyPair,
  CurrencyMap,
  CurrencyPairMap,
  OrderSide,
  OrderType,
  OrderStatus,
  ActiveOrderState,
  HistoricalOrderState,
  ActiveOrderType,
  HistoricalOrderType,
  TimeInForce,
  ExecutionInstruction,
  TriggerDirection,
  OrderTrigger,
  Order,
  OrderPlacementResult,
  LimitOrderConfig,
  MarketOrderConfig,
  PlaceOrderParams,
  ActiveOrdersOptions,
  HistoricalOrdersOptions,
  Trade,
  TradesOptions,
  Ticker,
  TickersOptions,
  Candle,
  CandlesOptions,
  OrderBookLevel,
  OrderBook,
  OrderBookOptions,
  TickerMetadata,
} from "./types/index.js";
